# Nook Shell - Input Configuration
# Keyboard, mouse, and touchpad settings.

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = false
    }

    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.
}
