# Nook Shell - Input Configuration
# Premium keyboard responsiveness and touchpad scroll acoustics.

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true
    
    # Ergonomic fluid key repeat settings
    repeat_delay = 250
    repeat_rate = 35

    # Mouse behaviors
    follow_mouse = 1
    off_window_axis_events = 2
    sensitivity = 0 # -1.0 to 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 0.7
        drag_lock = false
    }
}
