# Nook Shell - Workspaces Configuration
# Custom rules, static assignments, and behaviors for dynamic workspaces.

# Assign workspaces to specific monitors (optional / environment specific)
# workspace = 1, monitor:eDP-1, default:true
# workspace = 2, monitor:eDP-1, default:true

# Custom workspace rules for smart layouts
# workspace = name:dev, rounding:false, gapsin:0, gapsout:0
# workspace = name:reading, gapsin:10, gapsout:20

# --- Smart Gaps (No gaps, no borders, no rounding when only one tiled window is open) ---
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule = match:floating 0, match:workspace w[tv1], bordersize 0
windowrule = match:floating 0, match:workspace w[tv1], rounding 0
windowrule = match:floating 0, match:workspace f[1], bordersize 0
windowrule = match:floating 0, match:workspace f[1], rounding 0
